{
 "title": "VMware vSphere  - Overview",
 "description": "VMware vSphere Dashboard (Grafana 7.5 / new Time-Series Panel)",
 "tags": [
  "VMware",
  "vSphere Overview",
  "vSphere Telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "vcenter",
    "label": "vCenter Server",
    "query": "select DISTINCT(\"vcenter\") from (select \"usage_average\",\"vcenter\" from \"vsphere_host_cpu\" WHERE $timeFilter)"
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": "select DISTINCT(\"clustername\") from (select \"usage_average\",\"clustername\" from \"vsphere_host_cpu\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": "select DISTINCT(\"esxhostname\") from (select \"usage_average\",\"esxhostname\" from \"vsphere_host_cpu\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "select DISTINCT(\"dsname\") from (select \"used_latest\",\"dsname\" from \"vsphere_datastore_disk\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/ and \"dsname\"  !~ /MGMT*/ and \"dsname\"  !~ /COMPUTE*/ ) "
   },
   {
    "name": "virtualmachine",
    "label": "VM",
    "query": "select DISTINCT(\"vmname\") from (select \"ready_summation\",\"vmname\" from \"vsphere_vm_cpu\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vSphere Overview",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "vCenter Summary",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"vcenter\")) AS \"vCenter\" FROM (SELECT \"overhead_average\", \"vcenter\" FROM  \"vsphere_cluster_mem\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cluster Summary",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"clustername\")) AS \"Cluster\"  FROM (SELECT \"totalmhz_average\", \"clustername\" FROM  \"vsphere_cluster_cpu\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ESXi Summary",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"esxhostname\")) AS \"ESXi\" FROM (SELECT \"coreUtilization_average\", \"esxhostname\" FROM  \"vsphere_host_cpu\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "VM Summary",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"vmname\")) AS \"VM\" FROM (SELECT \"usage_average\", \"vmname\" FROM  \"vsphere_vm_cpu\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Datastore Summary",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"dsname\")) AS \"Datastore\" FROM (SELECT \"capacity_latest\", \"dsname\" FROM  \"vsphere_datastore_disk\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"uptime_latest\") AS \"Uptime\" FROM \"vsphere_host_sys\" WHERE (\"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($inter) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_average\") AS \"CPU Usage\" FROM \"vsphere_host_cpu\" WHERE (\"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/ AND \"cpu\" = 'instance-total') AND $timeFilter GROUP BY time($inter) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"usage_average\") AS \"RAM Usage\" FROM \"vsphere_host_mem\" WHERE (\"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($inter) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_clustername",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "SELECT last(\"usagemhz_average\") FROM \"vsphere_host_cpu\" WHERE (\"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($inter), \"clustername\" fill(none)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "instance-total" }
     ]
    }
   ]
  },
  {
   "title": "Cluster RAM Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_clustername",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "query": "SELECT last(\"totalCapacity_average\") * (last(\"usage_average\")) / 100 * 1024 FROM \"vsphere_host_mem\" WHERE  (\"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($inter), \"clustername\"  fill(none)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "Datastores - Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_source",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"used_latest\") * (100 / last(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) , \"source\"  fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$tag_clustername - Received",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($inter), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "bytesRx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "$tag_clustername - Transmited",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($inter), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "bytesTx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Storage Adapter",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_clustername - ReadAverage",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($inter), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "totalReadLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    },
    {
     "alias": "$tag_clustername - WriteAverage",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($inter), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "totalWriteLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
     ]
    }
   ]
  },
  {
   "title": "Datastore Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
     "repeat": "datastore",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    },
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "SELECT mean(\"used_latest\") * (100 / mean(\"capacity_latest\"))  FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($inter) fill(none)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Hypervisor Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hypervisor CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_esxhostname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($inter), \"host\" fill(none)",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "instance-total" }
       ]
      }
     ]
    },
    {
     "title": "Hypervisor Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_esxhostname mem usage average",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "Hypervisor Net Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "alias": "$tag_esxhostname net usage average",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_net",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "vCenter CPU/RAM",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_vcenter CPU",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vcenter" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "instance-total" }
       ]
      },
      {
       "alias": "$tag_vcenter RAM",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vcenter" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Machine CPU Usage in %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "instance-total" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Memory Usage Avg.",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine CPU READY ms",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "query": "SELECT mean(\"ready_summation\") FROM \"vsphere_vm_cpu\" WHERE (\"vmname\" =~ /^$virtualmachine$/) AND $timeFilter GROUP BY time($inter), \"vmname\" fill(none)",
       "select": [
        [
         { "params": [ "ready_summation" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Network Usage Avg (Kbps)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_net",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Disk Performance (Read VMFS Block IOPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_virtualDisk",
       "select": [
        [
         { "params": [ "numberReadAveraged_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Disk Performance (Write VMFS Block IOPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_virtualDisk",
       "select": [
        [
         { "params": [ "numberWriteAveraged_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Disk Performance (Block Latency Total)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_virtualDisk",
       "select": [
        [
         { "params": [ "totalReadLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_virtualDisk",
       "select": [
        [
         { "params": [ "totalWriteLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}